// <auto-generated />
using System;
using Economic.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Economic.Data.Migrations
{
    [DbContext(typeof(EconomicDbContext))]
    [Migration("20220628022043_AddDatabase")]
    partial class AddDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Economic.Data.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc"),
                            ConcurrencyStamp = "31f38468-f3de-42b5-af2d-c612558dc9cd",
                            Description = "Administrator role",
                            Name = "admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = new Guid("54ba416f-6b89-4c53-873d-4fbd48506e6d"),
                            ConcurrencyStamp = "3e7ae986-b6ea-4e57-a4da-36c367a20c3b",
                            Description = "Customer role",
                            Name = "customer",
                            NormalizedName = "customer"
                        });
                });

            modelBuilder.Entity("Economic.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("default-avatar.png");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RegisteredDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            AccessFailedCount = 0,
                            Address = "Vinh Long",
                            ConcurrencyStamp = "75a77216-b988-4bf7-bc2e-683728c583fd",
                            Email = "thong@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Nguyen Hoang Thong",
                            NormalizedEmail = "thong@gmail.com",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAEAn3+PYak4S6/gO9TL3c/9Wt+BcEXg0+/NfHUbVJTiIYgD3OGV8uDt+OXQ16Z4xoJQ==",
                            PhoneNumberConfirmed = false,
                            RegisteredDate = new DateTime(2022, 6, 28, 9, 20, 42, 751, DateTimeKind.Local).AddTicks(9106),
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("bff91064-dc92-421e-a233-d1080f630928"),
                            AccessFailedCount = 0,
                            Address = "Can Tho",
                            ConcurrencyStamp = "bfd391d5-a852-4f66-a948-486f4ca08ae8",
                            Email = "customer1@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Nguyen Hoang Thong Customer",
                            NormalizedEmail = "customer1@gmail.com",
                            NormalizedUserName = "customer",
                            PasswordHash = "AQAAAAEAACcQAAAAENs98V6vd/wbRB9BmGTbTPLJUR9FTaJ5pZ6CS+r1Vna1q5ePQ0OoOoILq442WgDrJg==",
                            PhoneNumberConfirmed = false,
                            RegisteredDate = new DateTime(2022, 6, 28, 9, 20, 42, 753, DateTimeKind.Local).AddTicks(5629),
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "customer1"
                        },
                        new
                        {
                            Id = new Guid("bff91054-dc92-421e-a233-d1080f630928"),
                            AccessFailedCount = 0,
                            Address = "TP HCM",
                            ConcurrencyStamp = "cd61fb9e-7070-4ef6-9b8c-2dd3807d764c",
                            Email = "customer2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "David",
                            NormalizedEmail = "customer2@gmail.com",
                            NormalizedUserName = "customer",
                            PasswordHash = "AQAAAAEAACcQAAAAEMczglLuZYhKCyGAHYsCdX/rTIo2pNLDIrY/CYxIsiXnDwG3lqq5bs2v7ueWdafIbw==",
                            PhoneNumberConfirmed = false,
                            RegisteredDate = new DateTime(2022, 6, 28, 9, 20, 42, 755, DateTimeKind.Local).AddTicks(2289),
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "customer2"
                        });
                });

            modelBuilder.Entity("Economic.Data.Entities.Cart", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("ProductId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Economic.Data.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Star")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Nồi tạm ổn",
                            Created = new DateTime(2022, 6, 28, 9, 20, 42, 755, DateTimeKind.Local).AddTicks(2320),
                            ProductId = 1,
                            Star = 5,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 2,
                            Content = "Sản phẩm tốt",
                            Created = new DateTime(2022, 6, 28, 9, 20, 42, 755, DateTimeKind.Local).AddTicks(2322),
                            ProductId = 1,
                            Star = 4,
                            UserId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de")
                        },
                        new
                        {
                            Id = 3,
                            Content = "Chất lượng ổn",
                            Created = new DateTime(2022, 6, 28, 9, 20, 42, 755, DateTimeKind.Local).AddTicks(2323),
                            ProductId = 2,
                            Star = 3,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 4,
                            Content = "Tạm ổn",
                            Created = new DateTime(2022, 6, 28, 9, 20, 42, 755, DateTimeKind.Local).AddTicks(2325),
                            ProductId = 2,
                            Star = 2,
                            UserId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de")
                        },
                        new
                        {
                            Id = 5,
                            Content = "Nồi tạm ổn",
                            Created = new DateTime(2022, 6, 28, 9, 20, 42, 755, DateTimeKind.Local).AddTicks(2326),
                            ProductId = 3,
                            Star = 1,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 6,
                            Content = "Tốt lắm",
                            Created = new DateTime(2022, 6, 28, 9, 20, 42, 755, DateTimeKind.Local).AddTicks(2328),
                            ProductId = 7,
                            Star = 5,
                            UserId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de")
                        },
                        new
                        {
                            Id = 7,
                            Content = "Tàm tạm",
                            Created = new DateTime(2022, 6, 28, 9, 20, 42, 755, DateTimeKind.Local).AddTicks(2329),
                            ProductId = 7,
                            Star = 3,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 8,
                            Content = "Ổn áp",
                            Created = new DateTime(2022, 6, 28, 9, 20, 42, 755, DateTimeKind.Local).AddTicks(2331),
                            ProductId = 8,
                            Star = 4,
                            UserId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de")
                        },
                        new
                        {
                            Id = 9,
                            Content = "Tốt",
                            Created = new DateTime(2022, 6, 28, 9, 20, 42, 755, DateTimeKind.Local).AddTicks(2332),
                            ProductId = 9,
                            Star = 2,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 10,
                            Content = "Sản phẩm ổn",
                            Created = new DateTime(2022, 6, 28, 9, 20, 42, 755, DateTimeKind.Local).AddTicks(2333),
                            ProductId = 10,
                            Star = 3,
                            UserId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de")
                        });
                });

            modelBuilder.Entity("Economic.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OrderDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryDate = new DateTime(2021, 5, 21, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2021, 5, 21, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 2,
                            DeliveryDate = new DateTime(2021, 5, 22, 10, 50, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2021, 5, 22, 13, 41, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 3,
                            DeliveryDate = new DateTime(2021, 5, 23, 9, 34, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2021, 5, 22, 15, 23, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 4,
                            DeliveryDate = new DateTime(2021, 5, 23, 16, 23, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2021, 5, 23, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            UserId = new Guid("bff91054-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 5,
                            OrderDate = new DateTime(2021, 5, 24, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 6,
                            OrderDate = new DateTime(2021, 5, 24, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            UserId = new Guid("bff91054-dc92-421e-a233-d1080f630928")
                        });
                });

            modelBuilder.Entity("Economic.Data.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ProductId = 1,
                            Amount = 2
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 2,
                            Amount = 1
                        },
                        new
                        {
                            OrderId = 3,
                            ProductId = 3,
                            Amount = 1
                        },
                        new
                        {
                            OrderId = 3,
                            ProductId = 1,
                            Amount = 2
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = 1,
                            Amount = 1
                        },
                        new
                        {
                            OrderId = 5,
                            ProductId = 3,
                            Amount = 1
                        },
                        new
                        {
                            OrderId = 5,
                            ProductId = 2,
                            Amount = 1
                        },
                        new
                        {
                            OrderId = 6,
                            ProductId = 4,
                            Amount = 1
                        });
                });

            modelBuilder.Entity("Economic.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 6, 28, 9, 20, 42, 750, DateTimeKind.Local).AddTicks(2190),
                            Description = "Nồi cơm nắp gài thiết kế đẹp mắt đáp ứng nhu cầu nấu cơm cơ bản; Nấu cơm chín nhanh chóng qua công nghệ nấu 1D, công suất 500W",
                            Name = "Nồi cơm nắp gài Kangaroo 1.5 lít KG825",
                            Price = 950000m,
                            ProductTypeId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 6, 28, 9, 20, 42, 750, DateTimeKind.Local).AddTicks(2202),
                            Description = "Nấu cơm thơm ngon, chín đều nhờ công nghệ nấu gia nhiệt tuần hoàn; Gia nhiệt đều, nấu cơm nhanh, giữ ấm lâu với công suất 860W cùng lòng nồi dạng niêu",
                            Name = "Nồi cơm điện tử Joyoung 1.8 lít F-50FY13",
                            Price = 1790000m,
                            ProductTypeId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 6, 28, 9, 20, 42, 750, DateTimeKind.Local).AddTicks(2203),
                            Description = "Nồi cơm nắp gài nhỏ gọn, đẹp mắt phù hợp cho nhu cầu nấu cơm cơ bản; Nấu cơm chín đều, tơi xốp, thơm ngon nhớ công nghệ nấu 1D, công suất 900W",
                            Name = "Nồi cơm nắp gài Kangaroo 2.2 lít KG829",
                            Price = 1150000m,
                            ProductTypeId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 6, 28, 9, 20, 42, 750, DateTimeKind.Local).AddTicks(2205),
                            Description = "Nồi cơm nắp gài nhỏ gọn, đẹp mắt sử dụng cho nhu cầu nấu cơm cơ bản; Nấu cơm chín đều, tơi xốp, thơm ngon nhờ công nghệ nấu 3D",
                            Name = "Nồi cơm nắp gài Kangaroo 1.2 lít KG822",
                            Price = 900000m,
                            ProductTypeId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 6, 28, 9, 20, 42, 750, DateTimeKind.Local).AddTicks(2206),
                            Description = "Nồi cơm nắp gài thiết kế đẹp mắt đáp ứng nhu cầu nấu cơm cơ bản; Nấu cơm chín nhanh đều, tơi xốp, thơm ngon nhờ công nghệ nấu 3D",
                            Name = "Nồi cơm nắp gài Delites 1.8 lít NCG1010",
                            Price = 790000m,
                            ProductTypeId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 6, 28, 9, 20, 42, 750, DateTimeKind.Local).AddTicks(2207),
                            Description = "Nồi cơm nắp gài thiết kế nổi bật phù hợp cho nhu cầu nấu cơm cơ bản; Cơm nấu nhín ngon, nhanh chóng qua công nghệ nấu 1D, công suất 700W",
                            Name = "Nồi cơm nắp gài Kangaroo 2.2 lít KG572",
                            Price = 890000m,
                            ProductTypeId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2022, 6, 28, 9, 20, 42, 750, DateTimeKind.Local).AddTicks(2208),
                            Description = "Thiết kế đơn giản, màu sắc trẻ trung; Công nghệ nấu 1D, công suất 700W truyền nhiệt từ đáy nồi, cơm chín nhanh",
                            Name = "Nồi cơm nắp gài Ava 1.8 lít NCG1806",
                            Price = 720000m,
                            ProductTypeId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2022, 6, 28, 9, 20, 42, 750, DateTimeKind.Local).AddTicks(2209),
                            Description = "Thiết kế màu cam tơi tắn, nhỏ gọn; Công nghệ nấu 1D nấu chín từ 20 - 30 phút",
                            Name = "Nồi cơm điện Midea 0.6 lít MR-CM06SD",
                            Price = 590000m,
                            ProductTypeId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2022, 6, 28, 9, 20, 42, 750, DateTimeKind.Local).AddTicks(2210),
                            Description = "Đáp ứng nhu cầu pha cà phê, nấu mì… với dung tích 1.5 lít; Nấu nước sôi nhanh 5- 7  phút với công suất 1500W",
                            Name = "Bình đun siêu tốc Delites 1.5 lít ST15S01",
                            Price = 170000m,
                            ProductTypeId = 2,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2022, 6, 28, 9, 20, 42, 750, DateTimeKind.Local).AddTicks(2210),
                            Description = "Nấu cơm thơm ngon, chín đều nhờ công nghệ nấu gia nhiệt tuần hoàn; Gia nhiệt đều, nấu cơm nhanh, giữ ấm lâu với công suất 860W cùng lòng nồi dạng niêu",
                            Name = "Nồi cơm điện tử Joyoung 1.8 lít F-50FY13",
                            Price = 1790000m,
                            ProductTypeId = 2,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2022, 6, 28, 9, 20, 42, 750, DateTimeKind.Local).AddTicks(2211),
                            Description = "Nồi cơm nắp gài nhỏ gọn, đẹp mắt phù hợp cho nhu cầu nấu cơm cơ bản; Nấu cơm chín đều, tơi xốp, thơm ngon nhớ công nghệ nấu 1D, công suất 900W",
                            Name = "Nồi cơm nắp gài Kangaroo 2.2 lít KG829",
                            Price = 1150000m,
                            ProductTypeId = 2,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2022, 6, 28, 9, 20, 42, 750, DateTimeKind.Local).AddTicks(2212),
                            Description = "Nồi cơm nắp gài nhỏ gọn, đẹp mắt sử dụng cho nhu cầu nấu cơm cơ bản; Nấu cơm chín đều, tơi xốp, thơm ngon nhờ công nghệ nấu 3D",
                            Name = "Nồi cơm nắp gài Kangaroo 1.2 lít KG822",
                            Price = 900000m,
                            ProductTypeId = 2,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2022, 6, 28, 9, 20, 42, 750, DateTimeKind.Local).AddTicks(2213),
                            Description = "Nồi cơm nắp gài thiết kế đẹp mắt đáp ứng nhu cầu nấu cơm cơ bản; Nấu cơm chín nhanh đều, tơi xốp, thơm ngon nhờ công nghệ nấu 3D",
                            Name = "Nồi cơm nắp gài Delites 1.8 lít NCG1010",
                            Price = 790000m,
                            ProductTypeId = 2,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2022, 6, 28, 9, 20, 42, 750, DateTimeKind.Local).AddTicks(2214),
                            Description = "Nồi cơm nắp gài thiết kế nổi bật phù hợp cho nhu cầu nấu cơm cơ bản; Cơm nấu nhín ngon, nhanh chóng qua công nghệ nấu 1D, công suất 700W",
                            Name = "Nồi cơm nắp gài Kangaroo 2.2 lít KG572",
                            Price = 890000m,
                            ProductTypeId = 2,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2022, 6, 28, 9, 20, 42, 750, DateTimeKind.Local).AddTicks(2217),
                            Description = "Thiết kế đơn giản, màu sắc trẻ trung; Công nghệ nấu 1D, công suất 700W truyền nhiệt từ đáy nồi, cơm chín nhanh",
                            Name = "Nồi cơm nắp gài Ava 1.8 lít NCG1806",
                            Price = 720000m,
                            ProductTypeId = 2,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2022, 6, 28, 9, 20, 42, 750, DateTimeKind.Local).AddTicks(2218),
                            Description = "Thiết kế màu cam tơi tắn, nhỏ gọn; Công nghệ nấu 1D nấu chín từ 20 - 30 phút",
                            Name = "Nồi cơm điện Midea 0.6 lít MR-CM06SD",
                            Price = 590000m,
                            ProductTypeId = 2,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Economic.Data.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            ProductPath = "1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 1,
                            ProductPath = "1.1.jpg"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 1,
                            ProductPath = "1.2.jpg"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 1,
                            ProductPath = "1.3.jpg"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 2,
                            ProductPath = "2.jpg"
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 2,
                            ProductPath = "2.1.jpg"
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 2,
                            ProductPath = "2.2.jpg"
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 2,
                            ProductPath = "2.3.jpg"
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 3,
                            ProductPath = "3.jpg"
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 3,
                            ProductPath = "3.1.jpg"
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 3,
                            ProductPath = "3.2.jpg"
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 3,
                            ProductPath = "3.3.jpg"
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 4,
                            ProductPath = "4.jpg"
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 4,
                            ProductPath = "4.1.jpg"
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 4,
                            ProductPath = "4.2.jpg"
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 4,
                            ProductPath = "4.3.jpg"
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 5,
                            ProductPath = "5.jpg"
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 5,
                            ProductPath = "5.1.jpg"
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 5,
                            ProductPath = "5.2.jpg"
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 5,
                            ProductPath = "5.3.jpg"
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 6,
                            ProductPath = "6.jpg"
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 6,
                            ProductPath = "6.1.jpg"
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 6,
                            ProductPath = "6.2.jpg"
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 6,
                            ProductPath = "6.3.jpg"
                        },
                        new
                        {
                            Id = 25,
                            ProductId = 7,
                            ProductPath = "7.jpg"
                        },
                        new
                        {
                            Id = 26,
                            ProductId = 7,
                            ProductPath = "7.1.jpg"
                        },
                        new
                        {
                            Id = 27,
                            ProductId = 7,
                            ProductPath = "7.2.jpg"
                        },
                        new
                        {
                            Id = 28,
                            ProductId = 7,
                            ProductPath = "7.3.jpg"
                        },
                        new
                        {
                            Id = 29,
                            ProductId = 8,
                            ProductPath = "8.jpg"
                        },
                        new
                        {
                            Id = 30,
                            ProductId = 8,
                            ProductPath = "8.1.jpg"
                        },
                        new
                        {
                            Id = 31,
                            ProductId = 8,
                            ProductPath = "8.2.jpg"
                        },
                        new
                        {
                            Id = 32,
                            ProductId = 8,
                            ProductPath = "8.3.jpg"
                        },
                        new
                        {
                            Id = 33,
                            ProductId = 9,
                            ProductPath = "9.jpg"
                        },
                        new
                        {
                            Id = 34,
                            ProductId = 9,
                            ProductPath = "9.1.jpg"
                        },
                        new
                        {
                            Id = 35,
                            ProductId = 9,
                            ProductPath = "9.2.jpg"
                        },
                        new
                        {
                            Id = 36,
                            ProductId = 9,
                            ProductPath = "9.3.jpg"
                        },
                        new
                        {
                            Id = 37,
                            ProductId = 10,
                            ProductPath = "10.jpg"
                        },
                        new
                        {
                            Id = 38,
                            ProductId = 10,
                            ProductPath = "10.1.jpg"
                        },
                        new
                        {
                            Id = 39,
                            ProductId = 10,
                            ProductPath = "10.2.jpg"
                        },
                        new
                        {
                            Id = 40,
                            ProductId = 10,
                            ProductPath = "10.3.jpg"
                        },
                        new
                        {
                            Id = 41,
                            ProductId = 11,
                            ProductPath = "11.jpg"
                        },
                        new
                        {
                            Id = 42,
                            ProductId = 11,
                            ProductPath = "11.1.jpg"
                        },
                        new
                        {
                            Id = 43,
                            ProductId = 11,
                            ProductPath = "11.2.jpg"
                        },
                        new
                        {
                            Id = 44,
                            ProductId = 11,
                            ProductPath = "11.3.jpg"
                        },
                        new
                        {
                            Id = 45,
                            ProductId = 12,
                            ProductPath = "12.jpg"
                        },
                        new
                        {
                            Id = 46,
                            ProductId = 12,
                            ProductPath = "12.1.jpg"
                        },
                        new
                        {
                            Id = 47,
                            ProductId = 12,
                            ProductPath = "12.2.jpg"
                        },
                        new
                        {
                            Id = 48,
                            ProductId = 12,
                            ProductPath = "12.3.jpg"
                        },
                        new
                        {
                            Id = 49,
                            ProductId = 13,
                            ProductPath = "13.jpg"
                        },
                        new
                        {
                            Id = 50,
                            ProductId = 13,
                            ProductPath = "13.1.jpg"
                        },
                        new
                        {
                            Id = 51,
                            ProductId = 13,
                            ProductPath = "13.2.jpg"
                        },
                        new
                        {
                            Id = 52,
                            ProductId = 13,
                            ProductPath = "13.3.jpg"
                        },
                        new
                        {
                            Id = 53,
                            ProductId = 14,
                            ProductPath = "14.jpg"
                        },
                        new
                        {
                            Id = 54,
                            ProductId = 14,
                            ProductPath = "14.1.jpg"
                        },
                        new
                        {
                            Id = 55,
                            ProductId = 14,
                            ProductPath = "14.2.jpg"
                        },
                        new
                        {
                            Id = 56,
                            ProductId = 14,
                            ProductPath = "14.3.jpg"
                        },
                        new
                        {
                            Id = 57,
                            ProductId = 15,
                            ProductPath = "15.jpg"
                        },
                        new
                        {
                            Id = 58,
                            ProductId = 15,
                            ProductPath = "15.1.jpg"
                        },
                        new
                        {
                            Id = 59,
                            ProductId = 15,
                            ProductPath = "15.2.jpg"
                        },
                        new
                        {
                            Id = 60,
                            ProductId = 15,
                            ProductPath = "15.3.jpg"
                        },
                        new
                        {
                            Id = 61,
                            ProductId = 16,
                            ProductPath = "16.jpg"
                        },
                        new
                        {
                            Id = 62,
                            ProductId = 16,
                            ProductPath = "16.1.jpg"
                        },
                        new
                        {
                            Id = 63,
                            ProductId = 16,
                            ProductPath = "16.2.jpg"
                        },
                        new
                        {
                            Id = 64,
                            ProductId = 16,
                            ProductPath = "16.3.jpg"
                        });
                });

            modelBuilder.Entity("Economic.Data.Entities.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Mang đến những bửa cơm đầy dinh dưỡng cho gia đình bạn",
                            Name = "Nồi cơm điện"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Giải pháp hiệu quả cho người bận rộn",
                            Name = "Ấm đun siêu tốc"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lựa chọn tốt nhất hàng đàu mang lại vitamin trái cây",
                            Name = "Máy xay sinh tố"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Chắc lọc sự tinh túy từ thiện nhiên trong ly nước ép",
                            Name = "Máy ép trái cây"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Cắt giảm lượng dầu mỡ tối đa cho gia đình bạn",
                            Name = "Nồi chiên không dầu"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Sự lựa chọn tối ưu cho bửa xum họp gia đình",
                            Name = "Lẩu điện"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Những buổi tiệc nướng đầy ấm áp bên người thân được mang lại",
                            Name = "Bếp nướng"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Căn bếp đầy tiện nghi và sang trọng khi có mặt sản phẩm này",
                            Name = "Bếp hồng ngoại"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AppUserRole", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            RoleId = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc")
                        },
                        new
                        {
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928"),
                            RoleId = new Guid("54ba416f-6b89-4c53-873d-4fbd48506e6d")
                        },
                        new
                        {
                            UserId = new Guid("bff91054-dc92-421e-a233-d1080f630928"),
                            RoleId = new Guid("54ba416f-6b89-4c53-873d-4fbd48506e6d")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens", (string)null);
                });

            modelBuilder.Entity("Economic.Data.Entities.Cart", b =>
                {
                    b.HasOne("Economic.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Economic.Data.Entities.AppUser", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Economic.Data.Entities.Comment", b =>
                {
                    b.HasOne("Economic.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Economic.Data.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Economic.Data.Entities.Order", b =>
                {
                    b.HasOne("Economic.Data.Entities.AppUser", null)
                        .WithMany("Orders")
                        .HasForeignKey("AppUserId");
                });

            modelBuilder.Entity("Economic.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("Economic.Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Economic.Data.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Economic.Data.Entities.Product", b =>
                {
                    b.HasOne("Economic.Data.Entities.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Economic.Data.Entities.ProductImage", b =>
                {
                    b.HasOne("Economic.Data.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Economic.Data.Entities.AppUser", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Economic.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Economic.Data.Entities.Product", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("Economic.Data.Entities.ProductType", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
